name: Common Test

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build23andnewer:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: ['24.3.4.6', '23.3.4.18']
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}

    - name: Compile
      run: rebar3 compile
    - name: Tests
      run: rebar3 ct --cover
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Covertool
      run: rebar3 covertool generate

    - uses: codecov/codecov-action@v1
      with:
        file: _build/test/covertool/grpcbox.covertool.xml

  build22andolder:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: ['22.3.4.20']
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
        rebar3-version: '3.18.0'

    - name: Compile
      run: rebar3 compile
    - name: Tests
      run: rebar3 ct --cover
    - name: Dialyzer
      run: rebar3 dialyzer
    - name: Covertool
      run: rebar3 covertool generate

    - uses: codecov/codecov-action@v1
      with:
        file: _build/test/covertool/grpcbox.covertool.xml
